# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kpture < Formula
  desc "kubernetes packet capture tool"
  homepage "https://github.com/gmtstephane/kpture"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gmtstephane/kpture/releases/download/v0.0.2/kpture_Darwin_x86_64.tar.gz"
      sha256 "4bfd3ac7ecc577f6c977359e44259ab490c16777766e1d5dd9a2d4ae8964f999"

      def install
        bin.install "kpture"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gmtstephane/kpture/releases/download/v0.0.2/kpture_Darwin_arm64.tar.gz"
      sha256 "71604d1bebab42584f259f505470e72a39948c779edf1e046aa50eae51bab4b7"

      def install
        bin.install "kpture"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gmtstephane/kpture/releases/download/v0.0.2/kpture_Linux_arm64.tar.gz"
      sha256 "09da5762afaf10f689c24c89d77fa6b7468ec4e282823238261f12b669b4d368"

      def install
        bin.install "kpture"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gmtstephane/kpture/releases/download/v0.0.2/kpture_Linux_x86_64.tar.gz"
      sha256 "1c56e58fc55ef3f387066510e2b93e2eff0d3735304a95f67db1d867ca2e56fd"

      def install
        bin.install "kpture"
      end
    end
  end
end
