# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kpture < Formula
  desc "kubernetes packet capture tool"
  homepage "https://github.com/gmtstephane/kpture"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gmtstephane/kpture/releases/download/v0.0.3/kpture_Darwin_arm64.tar.gz"
      sha256 "063874c72445b4b71ac9139deacc0331444957155c3e452760e1f45fb005bd80"

      def install
        bin.install "kpture"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gmtstephane/kpture/releases/download/v0.0.3/kpture_Darwin_x86_64.tar.gz"
      sha256 "4c2504037ce91f0c348ae4d90ec40316da209c3e91acca69583472a4fc4c5d4c"

      def install
        bin.install "kpture"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gmtstephane/kpture/releases/download/v0.0.3/kpture_Linux_arm64.tar.gz"
      sha256 "06d34bd6861432c3ce3af49d7c8fb13b77eef0f56c25f033150e6b4f0c15088a"

      def install
        bin.install "kpture"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gmtstephane/kpture/releases/download/v0.0.3/kpture_Linux_x86_64.tar.gz"
      sha256 "66a529783d322617c0157a2a3d24793ae0d40638b4460d03fb6b2de9e048a74a"

      def install
        bin.install "kpture"
      end
    end
  end
end
